using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutCategoryContainer : Collapsible
{
    public LoadoutCategoryContainer(string title)
    {
        RobustXamlLoader.Load(this);
        CategoryHeading.Title = Loc.GetString(title);
    }

    public void AddItem(Control item)
    {
        ItemsContainer.AddChild(item);
    }

}
