using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestUiFragment : BoxContainer
{
    [Dependency] private readonly SharedCrewManifestSystem _manifest = IoCManager.Resolve<IEntityManager>().System<SharedCrewManifestSystem>(); // Lonestar

    public CrewManifestUiFragment()
    {
        RobustXamlLoader.Load(this);

        StationName.AddStyleClass("LabelBig");
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(CrewManifestEntries? entries) // Coyote: remove name
    {
        CrewManifestListing.DisposeAllChildren();
        CrewManifestListing.RemoveAllChildren();

        StationNameContainer.Visible = entries != null;
        StationName.Text = "Crew Manifest"; // Coyote: remove name

        entries ??= _manifest.BuildCrewManifest(); // Lonestar
        CrewManifestListing.AddCrewManifestEntries(entries);
    }
}
