# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: CrateSlotMachine
  parent: CrateGenericSteel
  name: slot machine crate
  description: A crate with a slot machine inside, Everythng you need to start your own gambling addiction!
  components:
  - type: StorageFill
    contents:
      - id: SlotMachineFlatpack
